version: "3.7"

services:
    api:
        container_name: moura-backend
        image: phuong74200/moura
        restart: always
        depends_on:
            - mongodb
        ports:
            - 5000:5000
        environment:
            - DATABASE_NAME
            - CLIENT_URL
            - PORT
            - VERSION
            - DATABASE_URL=mongodb://mongodb:27017

    mongodb:
        container_name: moura-database
        image: mongo
        restart: always
        ports:
            - 27018:27017
        volumes:
            - mongo:/data/db
        restart: unless-stopped

volumes:
    mongo:
